/**
 * PRADEX - Frontend Configuration
 * Non-secret values only. Never put passwords, API secrets, or payment keys here.
 */
const CONFIG = {
    APP_NAME: "PRADEX",
    TAGLINE: "Build. Experiment. Innovate.",
    APPS_SCRIPT_URL: "https://script.google.com/macros/s/AKfycbx1-0ukdbWJl9vsFDhoEdNBjTglVTVNZf9Tyhr_19VKs_ezP7z_3O4SwXUfLDf38FAeYA/exec", // Replace after deploying Apps Script
    CURRENCY: "INR",
    CURRENCY_SYMBOL: "₹",
    DEMO_MODE: false, // Set to false for production
    OTP_EXPIRY_MINUTES: 5,
    FREE_SHIPPING_MIN: 999,
    DEFAULT_SHIPPING: 49,
    WHATSAPP: "919999999999", // Replace with real number
    EMAIL: "support@pradeeptechverse.com",
    PHONE: "+91 99999 99999",
    ADDRESS: "Chennai, Tamil Nadu, India",
    SOCIAL: {
        instagram: "#",
        youtube: "#",
        facebook: "#",
        twitter: "#"
    }
};

// Demo product data (used when DEMO_MODE and API not configured)
const DEMO_PRODUCTS = [
    {
        product_id: "PTV-ESP32-001",
        sku: "ESP32-DEVKIT-V1",
        name: "ESP32 Development Board",
        category: "ESP Boards",
        brand: "Generic",
        short_description: "Powerful dual-core Wi-Fi + Bluetooth microcontroller board for IoT projects.",
        description: "The ESP32 Development Board is a powerful, low-cost microcontroller with integrated Wi-Fi and dual-mode Bluetooth. Perfect for IoT, smart home, and embedded projects. Features dual-core processor, ample GPIO pins, and excellent community support.",
        original_price: 499,
        selling_price: 349,
        stock: 85,
        minimum_stock: 10,
        image_url: "https://via.placeholder.com/400x400/1a1a2e/00d4ff?text=ESP32",
        gallery_urls: [],
        specifications: "Microcontroller: ESP32 | Operating Voltage: 3.3V | Wi-Fi: 802.11 b/g/n | Bluetooth: v4.2 BR/EDR and BLE | GPIO: 30+ pins | Flash: 4MB | Input Voltage: 5V via USB",
        box_contents: "1 × ESP32 Development Board | 1 × USB Cable (optional)",
        warranty: "6 Months",
        guide_url: "",
        youtube_url: "",
        featured: true,
        best_seller: true,
        new_arrival: false,
        status: "active",
        created_at: "2026-01-15"
    },
    {
        product_id: "PTV-ESP8266-001",
        sku: "NODEMCU-ESP8266",
        name: "ESP8266 NodeMCU",
        category: "ESP Boards",
        brand: "NodeMCU",
        short_description: "Wi-Fi enabled microcontroller ideal for beginners and IoT prototypes.",
        description: "NodeMCU ESP8266 is a popular open-source IoT platform. It includes firmware that runs on the ESP8266 Wi-Fi SoC and hardware based on the ESP-12 module. Easy to program with Arduino IDE or Lua.",
        original_price: 299,
        selling_price: 199,
        stock: 120,
        minimum_stock: 15,
        image_url: "https://via.placeholder.com/400x400/1a1a2e/00ff88?text=ESP8266",
        gallery_urls: [],
        specifications: "Microcontroller: ESP8266 | Operating Voltage: 3.3V | Wi-Fi: 802.11 b/g/n | GPIO: 11 pins | Flash: 4MB | USB: Micro-USB",
        box_contents: "1 × NodeMCU ESP8266 Board",
        warranty: "6 Months",
        guide_url: "",
        youtube_url: "",
        featured: true,
        best_seller: true,
        new_arrival: false,
        status: "active",
        created_at: "2026-01-10"
    },
    {
        product_id: "PTV-ARD-001",
        sku: "ARDUINO-UNO-R3",
        name: "Arduino UNO R3",
        category: "Arduino",
        brand: "Arduino Compatible",
        short_description: "Classic Arduino UNO board – perfect starting point for electronics projects.",
        description: "Arduino UNO R3 is the most popular board for beginners. Based on ATmega328P, it has 14 digital I/O pins, 6 analog inputs, USB connection, power jack, and ICSP header. Compatible with Arduino IDE.",
        original_price: 599,
        selling_price: 449,
        stock: 60,
        minimum_stock: 10,
        image_url: "https://via.placeholder.com/400x400/1a1a2e/ff6b35?text=Arduino+UNO",
        gallery_urls: [],
        specifications: "Microcontroller: ATmega328P | Operating Voltage: 5V | Digital I/O: 14 | Analog Inputs: 6 | Flash: 32KB | Clock: 16MHz",
        box_contents: "1 × Arduino UNO R3 Compatible Board | 1 × USB Cable",
        warranty: "6 Months",
        guide_url: "",
        youtube_url: "",
        featured: true,
        best_seller: false,
        new_arrival: false,
        status: "active",
        created_at: "2026-01-05"
    },
    {
        product_id: "PTV-SEN-DHT11",
        sku: "DHT11-SENSOR",
        name: "DHT11 Temperature & Humidity Sensor",
        category: "Sensors",
        brand: "Generic",
        short_description: "Digital temperature and humidity sensor for Arduino and ESP projects.",
        description: "DHT11 is a basic, low-cost digital temperature and humidity sensor. It uses a capacitive humidity sensor and a thermistor to measure the surrounding air, and spits out a digital signal on the data pin.",
        original_price: 99,
        selling_price: 59,
        stock: 200,
        minimum_stock: 20,
        image_url: "https://via.placeholder.com/400x400/1a1a2e/ffd700?text=DHT11",
        gallery_urls: [],
        specifications: "Temperature Range: 0-50°C | Humidity: 20-90% RH | Accuracy: ±2°C / ±5% RH | Interface: Digital | Operating Voltage: 3.3-5V",
        box_contents: "1 × DHT11 Sensor Module",
        warranty: "3 Months",
        guide_url: "",
        youtube_url: "",
        featured: false,
        best_seller: true,
        new_arrival: false,
        status: "active",
        created_at: "2026-02-01"
    },
    {
        product_id: "PTV-SEN-HCSR04",
        sku: "HC-SR04-ULTRASONIC",
        name: "HC-SR04 Ultrasonic Distance Sensor",
        category: "Sensors",
        brand: "Generic",
        short_description: "Measure distance with ultrasonic waves – ideal for robotics and obstacle avoidance.",
        description: "HC-SR04 is a popular ultrasonic sensor that provides 2cm to 400cm non-contact measurement functionality. Perfect for robotics, parking sensors, and level detection projects.",
        original_price: 89,
        selling_price: 55,
        stock: 150,
        minimum_stock: 15,
        image_url: "https://via.placeholder.com/400x400/1a1a2e/00d4ff?text=HC-SR04",
        gallery_urls: [],
        specifications: "Range: 2cm - 400cm | Accuracy: 3mm | Operating Voltage: 5V | Trigger Pulse: 10µs | Measuring Angle: 15°",
        box_contents: "1 × HC-SR04 Ultrasonic Sensor",
        warranty: "3 Months",
        guide_url: "",
        youtube_url: "",
        featured: false,
        best_seller: true,
        new_arrival: false,
        status: "active",
        created_at: "2026-02-05"
    },
    {
        product_id: "PTV-SEN-PIR",
        sku: "PIR-MOTION-HC-SR501",
        name: "PIR Motion Sensor HC-SR501",
        category: "Sensors",
        brand: "Generic",
        short_description: "Passive infrared motion detector for security and automation projects.",
        description: "HC-SR501 PIR motion sensor detects movement of humans or animals within its range. Widely used in security systems, automatic lighting, and smart home applications.",
        original_price: 79,
        selling_price: 45,
        stock: 180,
        minimum_stock: 20,
        image_url: "https://via.placeholder.com/400x400/1a1a2e/ff00aa?text=PIR+Sensor",
        gallery_urls: [],
        specifications: "Detection Range: 3-7m | Angle: 120° | Operating Voltage: 4.5-20V | Output: Digital | Delay Time: Adjustable",
        box_contents: "1 × PIR Motion Sensor Module",
        warranty: "3 Months",
        guide_url: "",
        youtube_url: "",
        featured: false,
        best_seller: false,
        new_arrival: true,
        status: "active",
        created_at: "2026-03-01"
    },
    {
        product_id: "PTV-MOD-RELAY5V",
        sku: "RELAY-5V-1CH",
        name: "5V Single Channel Relay Module",
        category: "Modules",
        brand: "Generic",
        short_description: "Control high voltage devices with low voltage microcontrollers.",
        description: "5V relay module allows your Arduino, ESP32 or Raspberry Pi to control high-voltage appliances. Optocoupler isolation for safety. Supports both AC and DC loads.",
        original_price: 69,
        selling_price: 39,
        stock: 250,
        minimum_stock: 25,
        image_url: "https://via.placeholder.com/400x400/1a1a2e/00ff88?text=Relay+5V",
        gallery_urls: [],
        specifications: "Coil Voltage: 5V | Contact Rating: 10A 250VAC / 10A 30VDC | Optocoupler Isolation | Trigger: High/Low selectable",
        box_contents: "1 × 5V Relay Module",
        warranty: "3 Months",
        guide_url: "",
        youtube_url: "",
        featured: false,
        best_seller: true,
        new_arrival: false,
        status: "active",
        created_at: "2026-01-20"
    },
    {
        product_id: "PTV-ACC-BB",
        sku: "BREADBOARD-830",
        name: "830 Point Solderless Breadboard",
        category: "Components",
        brand: "Generic",
        short_description: "High-quality solderless breadboard for prototyping circuits.",
        description: "Standard 830-point breadboard for rapid prototyping. Features power rails on both sides. Compatible with all standard component leads and jumper wires.",
        original_price: 120,
        selling_price: 79,
        stock: 100,
        minimum_stock: 15,
        image_url: "https://via.placeholder.com/400x400/1a1a2e/ffffff?text=Breadboard",
        gallery_urls: [],
        specifications: "Points: 830 | Dimensions: ~165 × 55 mm | Material: ABS | Power Rails: Yes",
        box_contents: "1 × 830 Point Breadboard",
        warranty: "No Warranty",
        guide_url: "",
        youtube_url: "",
        featured: false,
        best_seller: false,
        new_arrival: false,
        status: "active",
        created_at: "2026-01-08"
    },
    {
        product_id: "PTV-ACC-JUMP",
        sku: "JUMPER-MALE-FEMALE-40",
        name: "Jumper Wire Pack (40 pcs Male-Female)",
        category: "Components",
        brand: "Generic",
        short_description: "Flexible male-to-female jumper wires for breadboard connections.",
        description: "Set of 40 flexible jumper wires (male to female). Essential for connecting sensors, modules and boards on breadboards without soldering.",
        original_price: 59,
        selling_price: 35,
        stock: 300,
        minimum_stock: 30,
        image_url: "https://via.placeholder.com/400x400/1a1a2e/ff6b35?text=Jumpers",
        gallery_urls: [],
        specifications: "Quantity: 40 pcs | Type: Male-Female | Length: ~20cm | Colors: Multicolor",
        box_contents: "40 × Male-Female Jumper Wires",
        warranty: "No Warranty",
        guide_url: "",
        youtube_url: "",
        featured: false,
        best_seller: true,
        new_arrival: false,
        status: "active",
        created_at: "2026-01-12"
    },
    {
        product_id: "PTV-ESP-CAM",
        sku: "ESP32-CAM",
        name: "ESP32-CAM Module",
        category: "ESP Boards",
        brand: "AI Thinker",
        short_description: "ESP32 with camera for video streaming, face recognition and IoT vision projects.",
        description: "ESP32-CAM is a small-size camera module based on ESP32. It features an OV2640 camera and provides onboard TF card slot. Perfect for DIY smart cameras, surveillance, and computer vision projects.",
        original_price: 699,
        selling_price: 549,
        stock: 40,
        minimum_stock: 8,
        image_url: "https://via.placeholder.com/400x400/1a1a2e/00d4ff?text=ESP32-CAM",
        gallery_urls: [],
        specifications: "Chip: ESP32 | Camera: OV2640 | Resolution: up to 1600x1200 | Flash: 4MB PSRAM | Wi-Fi + Bluetooth | TF Card Slot",
        box_contents: "1 × ESP32-CAM Module (without programmer)",
        warranty: "6 Months",
        guide_url: "",
        youtube_url: "",
        featured: true,
        best_seller: false,
        new_arrival: true,
        status: "active",
        created_at: "2026-03-10"
    },
    {
        product_id: "PTV-KIT-IOT",
        sku: "KIT-IOT-STARTER",
        name: "ESP32 IoT Starter Kit",
        category: "IoT Project Kits",
        brand: "PRADEX",
        short_description: "Complete beginner-friendly IoT kit with ESP32, sensors and project guides.",
        description: "Everything you need to start building IoT projects. Includes ESP32 board, sensors, breadboard, wires, and detailed Tamil + English project guides. Learn Wi-Fi, sensors, and cloud connectivity step by step.",
        original_price: 1499,
        selling_price: 999,
        stock: 25,
        minimum_stock: 5,
        image_url: "https://via.placeholder.com/400x400/1a1a2e/00ff88?text=IoT+Starter+Kit",
        gallery_urls: [],
        specifications: "Includes: ESP32, DHT11, HC-SR04, PIR, Relay, Breadboard, Jumpers, LEDs, Resistors | Guides: Tamil + English PDF",
        box_contents: "1 × ESP32 Board | 1 × DHT11 | 1 × HC-SR04 | 1 × PIR | 1 × 5V Relay | 1 × Breadboard | 40 Jumpers | LEDs & Resistors | Project Guide PDF",
        warranty: "6 Months on Electronics",
        guide_url: "",
        youtube_url: "",
        featured: true,
        best_seller: true,
        new_arrival: true,
        status: "active",
        created_at: "2026-03-15"
    },
    {
        product_id: "PTV-KIT-HOME",
        sku: "KIT-SMART-HOME",
        name: "Smart Home Automation Kit",
        category: "IoT Project Kits",
        brand: "PRADEX",
        short_description: "Build your own smart home with relays, sensors and ESP32 control.",
        description: "Create automated lighting, fan control, and motion-based security with this complete smart home kit. Includes ESP32, multi-channel relay, sensors and step-by-step guides.",
        original_price: 1899,
        selling_price: 1299,
        stock: 15,
        minimum_stock: 3,
        image_url: "https://via.placeholder.com/400x400/1a1a2e/ff00aa?text=Smart+Home+Kit",
        gallery_urls: [],
        specifications: "Includes: ESP32, 4-Channel Relay, DHT11, PIR, Push Buttons | App Control Ready | Tamil + English Guides",
        box_contents: "1 × ESP32 | 1 × 4-Channel Relay Module | 1 × DHT11 | 1 × PIR Sensor | Push Buttons | Wires | Project Guide",
        warranty: "6 Months on Electronics",
        guide_url: "",
        youtube_url: "",
        featured: true,
        best_seller: false,
        new_arrival: true,
        status: "active",
        created_at: "2026-03-20"
    }
];

const DEMO_CATEGORIES = [
    { category_id: "cat-esp", name: "ESP Boards", image_url: "https://via.placeholder.com/300x200/1a1a2e/00d4ff?text=ESP+Boards", status: "active" },
    { category_id: "cat-arduino", name: "Arduino", image_url: "https://via.placeholder.com/300x200/1a1a2e/ff6b35?text=Arduino", status: "active" },
    { category_id: "cat-sensors", name: "Sensors", image_url: "https://via.placeholder.com/300x200/1a1a2e/ffd700?text=Sensors", status: "active" },
    { category_id: "cat-modules", name: "Modules", image_url: "https://via.placeholder.com/300x200/1a1a2e/00ff88?text=Modules", status: "active" },
    { category_id: "cat-kits", name: "IoT Project Kits", image_url: "https://via.placeholder.com/300x200/1a1a2e/ff00aa?text=Project+Kits", status: "active" },
    { category_id: "cat-components", name: "Components", image_url: "https://via.placeholder.com/300x200/1a1a2e/ffffff?text=Components", status: "active" },
    { category_id: "cat-tools", name: "Tools", image_url: "https://via.placeholder.com/300x200/1a1a2e/00d4ff?text=Tools", status: "active" },
    { category_id: "cat-accessories", name: "Accessories", image_url: "https://via.placeholder.com/300x200/1a1a2e/ff6b35?text=Accessories", status: "active" }
];
